In [1]:
import numpy as np
from numpy.random import default_rng
rng = default_rng(seed=100)
ssp = [1, 0]
asp = [1, 0]
def epoch():
    tr = 0
    for _ in range(100):
        a = rng.choice(asp)
        s = rng.choice(ssp)
        if a == s:
            tr += 1
    return tr
rl = np.array([epoch() for _ in range(250)])
print(rl[:10])
print(rl.mean())

[56 47 48 55 55 51 54 43 55 40]
49.968


In [2]:
ssp = [1, 1, 1, 1, 0]
asp = [1, 0]
def epoch():
    tr = 0
    for _ in range(100):
        a = rng.choice(asp)
        s = rng.choice(ssp)
        if a == s:
            tr += 1
    return tr
rl = np.array([epoch() for _ in range(250)])
print(rl[:10])
print(rl.mean())

[53 56 40 55 53 49 43 45 50 51]
49.924


In [3]:
ssp = [1, 1, 1, 1, 0]
def epoch(n):
    tr = 0
    asp = [0, 1]
    for _ in range(n):
        a = rng.choice(asp)
        s = rng.choice(ssp)
        if a == s:
            tr += 1
        asp.append(s)
    return tr
rl = np.array([epoch(100) for _ in range(250)])
print(rl[:10])
print(rl.mean())

[71 65 67 69 68 72 68 68 77 73]
66.78


In [4]:
from collections import Counter
ssp = [1, 1, 1, 1, 0]
def epoch(n):
    tr = 0
    asp = [0, 1]
    for _ in range(n):
        c = Counter(asp)
        a = c.most_common()[0][0]
        s = rng.choice(ssp)
        if a == s:
            tr += 1
        asp.append(s)
    return tr
rl = np.array([epoch(100) for _ in range(250)])
print(rl[:10])
print(rl.mean())

[81 70 74 77 82 74 81 80 77 78]
78.828


In [5]:
ssp = [1, 2, 3, 4, 4, 4, 4, 4, 5, 6]
asp = [1, 2, 3, 4, 5, 6]
def epoch():
    tr = 0
    for _ in range(600):
        a = rng.choice(asp)
        s = rng.choice(ssp)
        if a == s:
            tr += 1
    return tr
rl = np.array([epoch() for _ in range(250)])
print(rl[:10])
print(rl.mean())

[ 92  96 106  99  96 107 101 106  92 117]
101.22


In [6]:
def epoch():
    tr = 0
    asp = [1, 2, 3, 4, 5, 6]
    for _ in range(600):
        a = rng.choice(asp)
        s = rng.choice(ssp)
        if a == s:
            tr += 1
        asp.append(s)
    return tr
rl = np.array([epoch() for _ in range(250)])
print(rl[:10])
print(rl.mean())

[182 174 162 157 184 167 190 208 171 153]
176.296


In [7]:
def epoch():
    tr = 0
    asp = [1, 2, 3, 4, 5, 6]
    for _ in range(600):
        c = Counter(asp)
        a = c.most_common()[0][0]
        s = rng.choice(ssp)
        if a == s:
            tr += 1
        asp.append(s)
    return tr
rl = np.array([epoch() for _ in range(250)])
print(rl[:10])
print(rl.mean())

[305 288 312 306 318 302 304 311 313 281]
297.204


In [8]:
from collections import Counter
ssp = [1, 0]
def epoch(n):
    tr = 0
    asp = [0, 1]
    for _ in range(n):
        c = Counter(asp)
        a = c.most_common()[0][0]
        s = rng.choice(ssp)
        if a == s:
            tr += 1
        asp.append(s)
    return tr
rl = np.array([epoch(100) for _ in range(250)])
print(rl[:10])
print(rl.mean())

[44 47 48 44 51 50 47 53 60 47]
50.264
